### ISSUE TITLE
mismatch of my data and your ToFFlythins3D

### ISSUE THREAD

**Issue by Hongdou68** [sylqiu/tof_rgbd_processing#5] opened 2020-03-27 10:38 UTC
Hi,Di Qiu:
               I am using the code which can generate the transient images and ground truth data. how ever when I repeate it in my machine, some problems occurs.
i am using the command line 'pbrt -**.pbrt' to generate the transient images of a special camera position. and using the command line'blender -b **.blend --python run_zpass_camera1_more.py' to generate the grund truth data. however when i am compared with your ToFFlytings3D dataset, some questions is here:
1:compare the transient images results with your GT data: I generarte the 20M depth using single frequency ,however my 20M depth is much larger than your data(in your .mat GT data,  GT*4*2/4095 to real depth), and the ration between your data and my 20M data is 1.4, it means that my 20M depth = 1.4 * your GT data, i don't known why this happened.
2: compare my GT data with your GT data: when compare my GT data with your GT data,some questions here, firstly i found the ration between my GT data and your GT data is about 12.5,secondly when i subtract 12.5*your GT data from my GT data ,a shift occured. you can see in this picture.
![6dc1134dd8183711acc04f35a286fd6](https://user-images.githubusercontent.com/25757403/77747671-061aab00-705a-11ea-8347-b2237154890c.jpg)

best regards

**Comment by Hongdou68** [comment] 2020-03-27 10:53
about generate GT data , i firstly using the run_zpass.....py file which in the folder, however the fov of the result is very large,so i add the 'fov = 63.5, scene.camera.data.angle = fov*（np.pi/180）',then the result is very similar with your given GT data, however some problems occured in above describe

**Comment by sylqiu** [comment] 2020-03-27 11:14
@Hongdou68 1. In making the dataset we have chosen different scaling across the scenes so that all the data are relatively of the same scale. Note that we have to be very careful about the scaling in .pbrt and .blender files to give rise to the correct results, since the geometry defined in these files are differed by some transformations. Perhaps you can check the world coordinate changes used within the blender python files? They are in general different for each scenes. If I remember correctly they should be the same with Su's datasets. I forgot but I probably had chosen further scaling when making my datasets. 2. Did you mean that the shift is caused by different fovs? That would be expected, since different fovs means the optical centers are at different locations.

**Comment by Hongdou68** [comment] 2020-03-27 11:28
Hi DIqiu: 
              the scale_factor in the more.pbrt and zpass python file is same , all is 0.1 in bathroom scene. so i do not known why.
the the picture you see is generated by the fov is 63.5 so the same problem, so do you use the 63.5 fov in your simulation?

**Comment by sylqiu** [comment] 2020-03-27 11:41
@Hongdou68 1. So that might be due to my own convention of making the dataset. I remember I clipped the depth by some value and normalize the range to be within [0,1] (or [0, 4095]). 
2. I used 63.5 in my simulation. You shift picture looks like the camera isn't at the correct location, so there seems a disparity particularly for near objects. Can you check your camera setup are exactly the same?

**Comment by Hongdou68** [comment] 2020-03-27 11:46
Hi, 1. I found the depth ration between my 20M depth data with your GT data is 1.4 ,so you means that you rescale of your GT data?
2: i copy the first 3 line from the camearpath.txt to camerapath_z.txt and then using blender to render the scene , i got the same result .

**Comment by sylqiu** [comment] 2020-03-27 15:36
@Hongdou68 1. Yes I have rescaled both ToF depth and GT depth. 2. After looking at the files camerapath.txt in the drive I think there is no problem on your part: the camerapath.txt included is "rounded-off" from the one I used when generating the data, causing the camera to be shifted. I have encountered similar things before, sorry for this bug. You should be able to generate aligned data using the blender and pbrt files though. I might not be able to release the correct unrounded camerapath.txt since I no longer had the access.

**Comment by Hongdou68** [comment] 2020-03-28 00:41
hi，1:you means  that you  scale the scene  twice，first when generated the transient images by pbrt and the gt depth by blender ，second  for  pbrt and blender results you found the tof depth and gt depth is larger than 4 meter then you rescsle it again ？
2: do you mean I have to genarate the unrounded campath.txt and campathz.txt ？I do not understand why you say generate these two txt  file should using round-off campath.txt and campath.txt.

**Comment by sylqiu** [comment] 2020-03-28 03:41
1. I clipped depth to some value which I define it to be 4 meters. 2. No, you can generate your data using the provided camera path, or any thing you want. Though that does not correspond to the dataset I create, because the provided camera path file is different from the one used to generate my dataset (i.e. I included the wrong file in the zip). For example, the original camera path value I used should be 1.2345678 but in the file it’s rounded to 1.235.

**Comment by Hongdou68** [comment] 2020-03-28 08:22
I known what you means, now I am using the campath.txt and campath_z.txt in your zip file to generate the ToF depth and the GT depth thoungh it is different with yours ToFFlythings 3D. but when i compare the ToF depth generated by pbrt and GT depth by blender , I found that these two depth not totally consistance not only in view perspective but also in depth range.
the picture 1 shows the ToF depth by pbrt(left) and GT depth by blender(right) ,
![acddff409f5bb611f012a67229c829c](https://user-images.githubusercontent.com/25757403/77818639-f1e4b580-710e-11ea-9f53-bb4f7caae51e.jpg)

the diff of thses two depth is in picture2.
![4744fe9092da6d97fb8d797f5449893](https://user-images.githubusercontent.com/25757403/77818643-f7420000-710e-11ea-94c0-d3eae439da5f.jpg)
 from the above the picture you can see the diff of these two depth in view perspective.
when i cal (GT depth/ToF depth) , the value hist is :
![839e3da27f1f6ceac6ca5a837e65603](https://user-images.githubusercontent.com/25757403/77818752-070e1400-7110-11ea-8155-52ab05abdae9.jpg)
AND I sure the campath used in pbrt and the campath_z used in blender are same. and the scale_factor is 0.1 in these case(the scene is bathroom). I do not known why.

**Comment by sylqiu** [comment] 2020-03-28 12:59
@Hongdou68 I see. It's pretty clear the problem is about the camera location. Can you try in blender setting, set the camera fov to be 63.5 and 63.74 and compare the results?

**Comment by Hongdou68** [comment] 2020-03-28 13:20
hi，I will try set the camera  fov in blender  tomorrow and compare  the results  with pbrt results. however the camera fov seems only influence the camera view  perspective .from the above  picture  I found the depth  range of pbrt results is much smaller than blender's results. the ratio between blender's  gt depth and port's   
tof depth  is about 9. the scale factor  is same 0.1

**Comment by Hongdou68** [comment] 2020-03-28 13:20
hi，I will try set the camera  fov in blender  tomorrow and compare  the results  with pbrt results. however the camera fov seems only influence the camera view  perspective .from the above  picture  I found the depth  range of pbrt results is much smaller than blender's results. the ratio between blender's  gt depth and port's   
tof depth  is about 9. the scale factor  is same 0.1

**Comment by sylqiu** [comment] 2020-03-28 15:06
@Hongdou68 Sorry, forget what I said about changing the fov experiment. I just did some experiment myself and I find no  misalignment between the two.
![blender](https://user-images.githubusercontent.com/24525023/77826107-730c6e80-7148-11ea-9621-9b5771872bfd.png)
![pbrt](https://user-images.githubusercontent.com/24525023/77826108-77388c00-7148-11ea-822f-28d817c2fc87.jpg)
The above one is rendered using blender and the bottom one using pbrt. I did not try to compute the depth, but they are certainly aligned. I'm not sure why do you get different results.
I'm not sure why you obtain different scales either, since I do not know what kind of method you used to obtain the depth from the transient, where the scale setting is up to you.

**Comment by Hongdou68** [comment] 2020-03-29 01:10
Hi, I check the program which used to generate tof depth from transient , and don't found any error. can you share with your 'scenes' folder with me through your google drive?

**Comment by Hongdou68** [comment] 2020-03-30 02:59
Hi,I have checked my GT depth and ToF depth again , I found the error might occured in the blender , and I get the GT depth by blender using your given 'run_z_pass_camera1_more.py',and your given 'more.blend'.




but the result is different with yours.

**Comment by Hongdou68** [comment] 2020-03-30 03:06
[bathroom.zip](https://github.com/sylqiu/tof_rgbd_processing/files/4400565/bathroom.zip)
the zip file contains the campath_z.txt and zpass file  which I have used to generate the GT depth. the results is different with yours , so I guess there must some parameters error in my script or some parameters setting missed in my blender file , can you help me check it again?

**Comment by sylqiu** [comment] 2020-03-30 06:34
@Hongdou68 My results were obtained by downloading my own repo and run the script in my newly installed Blender. I don't know why you've got different, it's possible that you changed some setting in Blender that is not covered in the script. Since there is no problem with my repo, I'm closing this issue.

**Closed** 2020-03-30 06:35 UTC
